### ISSUE TITLE
Question about post process result.

### ISSUE THREAD

**Issue by siyuada** [zhou13/lcnn#13] opened 2019-12-23 06:53 UTC
Hey, I noticed in your paper, using post process could help improve the AP^H. I tried to use that, however, there are not such gap between the results of no post and post processing. Here is my result:

![图片](https://user-images.githubusercontent.com/34361090/71340630-651be000-2592-11ea-8913-b6766d5f0923.png)

The result of LCNN net output: 
- F^H:  0.76836   AP^H is:  0.8026
The result of post process output: 
- F^H: 0.8011  AP^H: lcnn_post AP is:  0.80538
And the sAP is the same as the paper said. (No post process)

To see the result, it seems my results is good, could you please help me find the problem? Is there any step I forgot?

- Prepross Wireframe dataset
- Run Process
- Run Post

Below is the process result. First is GT, Second is LCNN net output, Third is result after post process, the result move overlap lines.
![00035610](https://user-images.githubusercontent.com/34361090/71341030-a06ade80-2593-11ea-9842-b9889267ba0f.jpg)

**Comment by zhou13** [comment] 2019-12-23 09:50
Hi @siyuada , Thank you for reporting your finding. I think what you observe might be expected. There was a bug fix introduced in #5, which might make the gap between no post and post-processing disappear. I will retest the result, and if I can reproduce it, I will update the paper (appendix) accordingly.

**Comment by siyuada** [comment] 2019-12-24 10:37
Thanks for your quick reply! By the way, I processed the dataset as below:

` im = cv2.imread(os.path.join(data_root, path))  `
` lines = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]]).reshape(-1,2,2) `


Look forward to your retest results. : )

**Comment by siyuada** [comment] 2020-01-09 09:20
Hey, I noticed In "plot-sAP.py", you use two different way to calculate sAP. One is used in wireframe, each threshold corresponds to a point in the PR curves. Another is used in AFM, L-CNN and lsd, which utilize the line score to make final results. 

I used the first method to cal L-CNN performance by default thresholds. However,  the sAP will droped . Especially, sAP^5: 58.9 -> 53.12;  sAP^10: 62.9 -> 56.89; sAP^15: 64.7 -> 58.63 ...

Could you give some explanations for that result? And In AFM method, what is the meaning of scores?  Can aspect ratio to be a confidence? (Also, if I test AFM in sAP by the method as evaluated in wireframe, the precision and recall value both mightily droped)

Hope for your help. Thanks for a lot.

**Comment by zhou13** [comment] 2020-01-11 07:43
Hey.  The original wireframe paper requires the first method because it does not give a score to each line. Instead, it uses a threshold to filter the heat map and then extract the lines from it. The second method is more accurate as it does not require pre-defined thresholds. 

But two methods should give the same result if you set the number of the thresholds large enough in the first method. It is possible that the drop in performance is due to the small number of thresholds because the curve is convex. Could you plot the sAP curve with two methods and compare them?

**Comment by zhou13** [comment] 2020-01-24 02:54
Hi @siyuada , I think I cannot reproduce your problem.  For the result without post processing, I have 
```
f measure is:  0.7691721201652405
AP is:  0.8026532651198798
```
For the result with post processing, I have
```
f measure is:  0.8124048668872935
AP is:  0.8274447327437309
```

Such result can be reproceduced by
```
./process.py config/wireframe.yaml  logs/190418-201834-f8934c6-lr4d10/npz/000312000/checkpoint.pth.tar   data/wireframe  post/190418-201834-f8934c6-lr4d10-312k-correct
./post.py --thresholds="0.002,0.006,0.010,0.015,0.02" post/190418-201834-f8934c6-lr4d10-312k-correct post/190418-201834-f8934c6-lr4d10-312k-correct-post
./eval-APH.py post/190418-201834-f8934c6-lr4d10-312k-correct /tmp
./eval-APH.py post/190418-201834-f8934c6-lr4d10-312k-correct-post/0_010 /tmp
```

The md5sum checksum of checkpoint and configure file is
```
$ md5sum logs/190418-201834-f8934c6-lr4d10/npz/000312000/checkpoint.pth.tar
55a7e9010dea139b6baa269afd513ccb  logs/190418-201834-f8934c6-lr4d10/npz/000312000/checkpoint.pth.tar
$ md5sum config/wireframe.yaml                                                               
1f79b424ae7387b28187f046eb51aa46  config/wireframe.yaml
```

The number should have already matched the README.md and the newest version of the paper.

**Comment by siyuada** [comment] 2020-01-24 02:58
hey, thanks for your reply.&nbsp; I have a question about the threshold used.&nbsp; I just use 0.01 to make that evaluation result.&nbsp; Is it lower threshold making the result better？



---Original---

**Comment by zhou13** [comment] 2020-01-24 03:03
I think I am also using 0.01 (`0_010`)

**Comment by siyuada** [comment] 2020-01-24 03:10
OK, I’ll try again.&nbsp;&nbsp;
Anyway, It is an excellent work！



---Original---

**Comment by zhou13** [comment] 2020-01-24 09:13
Thank you!

**Comment by zhou13** [comment] 2020-02-11 22:47
I would close this issue as it has been almost 3 weeks. Feel free to reopen this issue if you have updates.

**Closed as completed by zhou13** 2020-02-11 22:47 UTC
Labels: question
